// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Messenger.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__MESSENGER_MESSENGER_HPP
#define FAST_DDS_GENERATED__MESSENGER_MESSENGER_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MESSENGER_SOURCE)
#define MESSENGER_DllAPI __declspec( dllexport )
#else
#define MESSENGER_DllAPI __declspec( dllimport )
#endif // MESSENGER_SOURCE
#else
#define MESSENGER_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MESSENGER_DllAPI
#endif // _WIN32

namespace Messenger {

/*!
 * @brief This class represents the structure Message defined by the user in the IDL file.
 * @ingroup Messenger
 */
class Message
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Message()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Message()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Message that will be copied.
     */
    eProsima_user_DllExport Message(
            const Message& x)
    {
                    m_from = x.m_from;

                    m_subject = x.m_subject;

                    m_subject_id = x.m_subject_id;

                    m_text = x.m_text;

                    m_count = x.m_count;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Message that will be copied.
     */
    eProsima_user_DllExport Message(
            Message&& x) noexcept
    {
        m_from = std::move(x.m_from);
        m_subject = std::move(x.m_subject);
        m_subject_id = x.m_subject_id;
        m_text = std::move(x.m_text);
        m_count = x.m_count;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Message that will be copied.
     */
    eProsima_user_DllExport Message& operator =(
            const Message& x)
    {

                    m_from = x.m_from;

                    m_subject = x.m_subject;

                    m_subject_id = x.m_subject_id;

                    m_text = x.m_text;

                    m_count = x.m_count;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Message that will be copied.
     */
    eProsima_user_DllExport Message& operator =(
            Message&& x) noexcept
    {

        m_from = std::move(x.m_from);
        m_subject = std::move(x.m_subject);
        m_subject_id = x.m_subject_id;
        m_text = std::move(x.m_text);
        m_count = x.m_count;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Message object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Message& x) const
    {
        return (m_from == x.m_from &&
           m_subject == x.m_subject &&
           m_subject_id == x.m_subject_id &&
           m_text == x.m_text &&
           m_count == x.m_count);
    }

    /*!
     * @brief Comparison operator.
     * @param x Message object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Message& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member from
     * @param _from New value to be copied in member from
     */
    eProsima_user_DllExport void from(
            const std::string& _from)
    {
        m_from = _from;
    }

    /*!
     * @brief This function moves the value in member from
     * @param _from New value to be moved in member from
     */
    eProsima_user_DllExport void from(
            std::string&& _from)
    {
        m_from = std::move(_from);
    }

    /*!
     * @brief This function returns a constant reference to member from
     * @return Constant reference to member from
     */
    eProsima_user_DllExport const std::string& from() const
    {
        return m_from;
    }

    /*!
     * @brief This function returns a reference to member from
     * @return Reference to member from
     */
    eProsima_user_DllExport std::string& from()
    {
        return m_from;
    }


    /*!
     * @brief This function copies the value in member subject
     * @param _subject New value to be copied in member subject
     */
    eProsima_user_DllExport void subject(
            const std::string& _subject)
    {
        m_subject = _subject;
    }

    /*!
     * @brief This function moves the value in member subject
     * @param _subject New value to be moved in member subject
     */
    eProsima_user_DllExport void subject(
            std::string&& _subject)
    {
        m_subject = std::move(_subject);
    }

    /*!
     * @brief This function returns a constant reference to member subject
     * @return Constant reference to member subject
     */
    eProsima_user_DllExport const std::string& subject() const
    {
        return m_subject;
    }

    /*!
     * @brief This function returns a reference to member subject
     * @return Reference to member subject
     */
    eProsima_user_DllExport std::string& subject()
    {
        return m_subject;
    }


    /*!
     * @brief This function sets a value in member subject_id
     * @param _subject_id New value for member subject_id
     */
    eProsima_user_DllExport void subject_id(
            int32_t _subject_id)
    {
        m_subject_id = _subject_id;
    }

    /*!
     * @brief This function returns the value of member subject_id
     * @return Value of member subject_id
     */
    eProsima_user_DllExport int32_t subject_id() const
    {
        return m_subject_id;
    }

    /*!
     * @brief This function returns a reference to member subject_id
     * @return Reference to member subject_id
     */
    eProsima_user_DllExport int32_t& subject_id()
    {
        return m_subject_id;
    }


    /*!
     * @brief This function copies the value in member text
     * @param _text New value to be copied in member text
     */
    eProsima_user_DllExport void text(
            const std::string& _text)
    {
        m_text = _text;
    }

    /*!
     * @brief This function moves the value in member text
     * @param _text New value to be moved in member text
     */
    eProsima_user_DllExport void text(
            std::string&& _text)
    {
        m_text = std::move(_text);
    }

    /*!
     * @brief This function returns a constant reference to member text
     * @return Constant reference to member text
     */
    eProsima_user_DllExport const std::string& text() const
    {
        return m_text;
    }

    /*!
     * @brief This function returns a reference to member text
     * @return Reference to member text
     */
    eProsima_user_DllExport std::string& text()
    {
        return m_text;
    }


    /*!
     * @brief This function sets a value in member count
     * @param _count New value for member count
     */
    eProsima_user_DllExport void count(
            int32_t _count)
    {
        m_count = _count;
    }

    /*!
     * @brief This function returns the value of member count
     * @return Value of member count
     */
    eProsima_user_DllExport int32_t count() const
    {
        return m_count;
    }

    /*!
     * @brief This function returns a reference to member count
     * @return Reference to member count
     */
    eProsima_user_DllExport int32_t& count()
    {
        return m_count;
    }



private:

    std::string m_from;
    std::string m_subject;
    int32_t m_subject_id{0};
    std::string m_text;
    int32_t m_count{0};

};

} // namespace Messenger

#endif // _FAST_DDS_GENERATED_MESSENGER_MESSENGER_HPP_


