// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MessengerTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "MessengerTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "Messenger.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace Messenger {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Message_type_identifier(
        TypeIdentifierPair& type_ids_Message)
{

    ReturnCode_t return_code_Message {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Message =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Messenger::Message", type_ids_Message);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Message)
    {
        StructTypeFlag struct_flags_Message = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_Message = "Messenger::Message";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Message;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Message;
        AppliedAnnotationSeq tmp_ann_custom_Message;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_Message;
        if (!tmp_ann_custom_Message.empty())
        {
            ann_custom_Message = tmp_ann_custom_Message;
        }

        CompleteTypeDetail detail_Message = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Message, ann_custom_Message, type_name_Message.to_string());
        CompleteStructHeader header_Message;
        header_Message = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Message);
        CompleteStructMemberSeq member_seq_Message;
        {
            TypeIdentifierPair type_ids_from;
            ReturnCode_t return_code_from {eprosima::fastdds::dds::RETCODE_OK};
            return_code_from =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_from);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_from)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_from))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_from = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_from = 0x00000000;
            bool common_from_ec {false};
            CommonStructMember common_from {TypeObjectUtils::build_common_struct_member(member_id_from, member_flags_from, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_from, common_from_ec))};
            if (!common_from_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure from member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_from = "from";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_from;
            ann_custom_Message.reset();
            CompleteMemberDetail detail_from = TypeObjectUtils::build_complete_member_detail(name_from, member_ann_builtin_from, ann_custom_Message);
            CompleteStructMember member_from = TypeObjectUtils::build_complete_struct_member(common_from, detail_from);
            TypeObjectUtils::add_complete_struct_member(member_seq_Message, member_from);
        }
        {
            TypeIdentifierPair type_ids_subject;
            ReturnCode_t return_code_subject {eprosima::fastdds::dds::RETCODE_OK};
            return_code_subject =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_subject);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_subject)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_subject))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_subject = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_subject = 0x00000001;
            bool common_subject_ec {false};
            CommonStructMember common_subject {TypeObjectUtils::build_common_struct_member(member_id_subject, member_flags_subject, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_subject, common_subject_ec))};
            if (!common_subject_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure subject member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_subject = "subject";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_subject;
            ann_custom_Message.reset();
            CompleteMemberDetail detail_subject = TypeObjectUtils::build_complete_member_detail(name_subject, member_ann_builtin_subject, ann_custom_Message);
            CompleteStructMember member_subject = TypeObjectUtils::build_complete_struct_member(common_subject, detail_subject);
            TypeObjectUtils::add_complete_struct_member(member_seq_Message, member_subject);
        }
        {
            TypeIdentifierPair type_ids_subject_id;
            ReturnCode_t return_code_subject_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_subject_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_subject_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_subject_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "subject_id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_subject_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, true, false);
            MemberId member_id_subject_id = 0x00000002;
            bool common_subject_id_ec {false};
            CommonStructMember common_subject_id {TypeObjectUtils::build_common_struct_member(member_id_subject_id, member_flags_subject_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_subject_id, common_subject_id_ec))};
            if (!common_subject_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure subject_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_subject_id = "subject_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_subject_id;
            ann_custom_Message.reset();
            AppliedAnnotationSeq tmp_ann_custom_subject_id;
            eprosima::fastcdr::optional<std::string> unit_subject_id;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_subject_id;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_subject_id;
            eprosima::fastcdr::optional<std::string> hash_id_subject_id;
            if (unit_subject_id.has_value() || min_subject_id.has_value() || max_subject_id.has_value() || hash_id_subject_id.has_value())
            {
                member_ann_builtin_subject_id = TypeObjectUtils::build_applied_builtin_member_annotations(unit_subject_id, min_subject_id, max_subject_id, hash_id_subject_id);
            }
            if (!tmp_ann_custom_subject_id.empty())
            {
                ann_custom_Message = tmp_ann_custom_subject_id;
            }
            CompleteMemberDetail detail_subject_id = TypeObjectUtils::build_complete_member_detail(name_subject_id, member_ann_builtin_subject_id, ann_custom_Message);
            CompleteStructMember member_subject_id = TypeObjectUtils::build_complete_struct_member(common_subject_id, detail_subject_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_Message, member_subject_id);
        }
        {
            TypeIdentifierPair type_ids_text;
            ReturnCode_t return_code_text {eprosima::fastdds::dds::RETCODE_OK};
            return_code_text =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_text);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_text)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_text))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_text = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_text = 0x00000003;
            bool common_text_ec {false};
            CommonStructMember common_text {TypeObjectUtils::build_common_struct_member(member_id_text, member_flags_text, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_text, common_text_ec))};
            if (!common_text_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure text member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_text = "text";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_text;
            ann_custom_Message.reset();
            CompleteMemberDetail detail_text = TypeObjectUtils::build_complete_member_detail(name_text, member_ann_builtin_text, ann_custom_Message);
            CompleteStructMember member_text = TypeObjectUtils::build_complete_struct_member(common_text, detail_text);
            TypeObjectUtils::add_complete_struct_member(member_seq_Message, member_text);
        }
        {
            TypeIdentifierPair type_ids_count;
            ReturnCode_t return_code_count {eprosima::fastdds::dds::RETCODE_OK};
            return_code_count =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_count);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_count)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "count Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_count = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_count = 0x00000004;
            bool common_count_ec {false};
            CommonStructMember common_count {TypeObjectUtils::build_common_struct_member(member_id_count, member_flags_count, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_count, common_count_ec))};
            if (!common_count_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure count member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_count = "count";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_count;
            ann_custom_Message.reset();
            CompleteMemberDetail detail_count = TypeObjectUtils::build_complete_member_detail(name_count, member_ann_builtin_count, ann_custom_Message);
            CompleteStructMember member_count = TypeObjectUtils::build_complete_struct_member(common_count, detail_count);
            TypeObjectUtils::add_complete_struct_member(member_seq_Message, member_count);
        }
        CompleteStructType struct_type_Message = TypeObjectUtils::build_complete_struct_type(struct_flags_Message, header_Message, member_seq_Message);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Message, type_name_Message.to_string(), type_ids_Message))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Messenger::Message already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace Messenger

